<?php

namespace AppBundle\Repository\Proyecto;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectosEnEsperaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proyectosEnEsperaRepository extends EntityRepository
{
}
