<?php

namespace AppBundle\Repository;

/**
 * nodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class nodoRepository extends \Doctrine\ORM\EntityRepository
{
}
