<?php

namespace AppBundle\Repository;

/**
 * departamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class departamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
