<?php

namespace AppBundle\Repository\PrsoInterno;

use Doctrine\ORM\EntityRepository;

/**
 * ejecutivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ejecutivoRepository extends EntityRepository
{
}
