<?php

namespace AppBundle\Repository\PrsoInterno;

use Doctrine\ORM\EntityRepository;

/**
 * liderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class liderRepository extends EntityRepository
{
}
