<?php

namespace AppBundle\Repository\Cliente;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteGobiernoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteGobiernoDetalleRepository extends EntityRepository
{
}
