<?php

namespace AppBundle\Repository\Fase;;

use Doctrine\ORM\EntityRepository;

/**
 * fases_sipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FasesSipRepository extends EntityRepository
{
}
